cleanup

diff --git a/hooks/docker-compose b/hooks/docker-compose
--- a/hooks/docker-compose
+++ b/hooks/docker-compose
@@ -1,3 +1,5 @@
+# Read: For everything else besides the docker-compose command.
+
 set -eE
 
 trap 'exit_error' ERR
@@ -11,8 +13,69 @@ exit_error() {
 
 exit_zero() {
 
-    local placeholder=
+    local do_nothing=
 
 }
 
-portainer_container_id=$(docker ps -aqf "name=$PORTAINER_CONTAINER_NAME")
+if [ $1 = stack ]; then
+
+    if [ $2 = up ]; then
+
+        if [ $3 = begin ]; then
+
+            ####################################
+            #                                  #
+            #          DOCKER-COMPOSE          #
+            #                                  #
+            ####################################
+
+            # Test docker installation
+            ! which docker 1>/dev/null && echo "Please install docker." && exit 1
+
+            # Test environment vars
+            if [ -f .env ]; then
+
+                . .env
+
+            else
+
+                echo "Did you forget to symlink the appropriate .env file for your local machine?"
+                exit 1
+
+            fi
+
+            # Test specified uid
+            # ! id $PUID 1>/dev/null && echo "User id $PUID not found, exiting" && exit 1
+
+            #############################
+            #                           #
+            #          POLARIS          #
+            #                           #
+            #############################
+
+            # Test required directories
+            [ ! -d "$POLARIS_VOLUME_MUSIC" ] && echo "$POLARIS_VOLUME_MUSIC not found, exiting" && exit 1
+            [ ! -d "$POLARIS_VOLUME_CACHE" ] && echo "$POLARIS_VOLUME_CACHE not found, exiting" && exit 1
+            [ ! -d "$POLARIS_VOLUME_DATA"  ] && echo "$POLARIS_VOLUME_DATA not found, exiting"  && exit 1
+
+        elif [ $3 = end ]; then
+
+            local do_nothing=
+
+        fi
+
+    elif [ $2 = down ]; then
+
+        if [ $3 = begin ]; then
+
+            local do_nothing=
+
+        elif [ $3 = end ]; then
+
+            local do_nothing=
+
+        fi
+
+    fi
+
+fi
